# Generated by Django 4.2.6 on 2023-11-13 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='CoverageInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CoverageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'Coverage A'), ('B', 'Coverage B'), ('C', 'Coverage C')], max_length=25)),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CoverageTransactionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coverages.coveragegroup')),
                ('coverage_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coverages.coverageinstance')),
            ],
        ),
        migrations.AddField(
            model_name='coverageinstance',
            name='coverage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coverages.coveragetype'),
        ),
    ]
