# Generated by Django 4.2.6 on 2023-11-17 06:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        ('forms', '0001_initial'),
        ('coverages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(default=datetime.date.today)),
                ('expiration_date', models.DateField(null=True)),
                ('product', models.CharField(choices=[('HOME', "Homeowner's Insurance"), ('RENT', "Renter's Insurance")], default='RENT', max_length=25)),
                ('policy_type', models.CharField(choices=[('HO3', 'HO3'), ('HO4', 'HO4'), ('HO6', 'HO6')], default='HO4', max_length=10)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('number', models.CharField(default='Q10012023', max_length=25, null=True)),
                ('term', models.PositiveSmallIntegerField(null=True)),
                ('latest_claim_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='claims.claimgroup')),
                ('latest_coverage_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coverages.coveragegroup')),
                ('latest_form_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.formgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
