# Generated by Django 4.2.6 on 2023-10-25 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(default=datetime.date.today)),
                ('expiration_date', models.DateField()),
                ('product', models.CharField(choices=[('HOME', "Homeowner's Insurance"), ('RENT', "Renter's Insurance")], default=('RENT', "Renter's Insurance"), max_length=25)),
                ('type', models.CharField(choices=[('HO3', 'HO3'), ('HO4', 'HO4'), ('HO6', 'HO6')], default=('HO4', 'HO4'), max_length=3)),
            ],
        ),
    ]
