# Generated by Django 4.2.6 on 2023-11-17 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policies', '0001_initial'),
        ('risks', '0001_initial'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='originating_quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.quote'),
        ),
        migrations.AddField(
            model_name='policy',
            name='risk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='risks.risk'),
        ),
        migrations.AddField(
            model_name='policy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
