# Generated by Django 4.2.6 on 2023-11-17 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        ('forms', '0001_initial'),
        ('coverages', '0001_initial'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('premium_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(choices=[('NB', 'New Business'), ('RN', 'Renewal'), ('END', 'Endorsement'), ('I', 'Information'), ('C', 'Cancel')], max_length=5)),
                ('claim_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='claims.claimgroup')),
                ('coverage_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coverages.coveragegroup')),
                ('form_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.formgroup')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.policy')),
            ],
        ),
    ]
