# Generated by Django 4.2.6 on 2023-10-23 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0001_initial'),
        ('quotes', '0002_rename_property_risk_rename_property_quote_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.risk'),
        ),
        migrations.DeleteModel(
            name='Risk',
        ),
    ]
